"""Generate the runtime rod-group table using only the Python standard library."""
import ast
import csv
import io
import json
import re
import urllib.request
from fractions import Fraction
from pathlib import Path

REVISION = "fbeb69cd9914cf7703604bc17d26c3b9b45aee49"
BASE = f"https://raw.githubusercontent.com/qzhu2017/PyXtal/{REVISION}/"
ROOT = Path(__file__).resolve().parents[1]


def read(path):
    return urllib.request.urlopen(BASE + path).read().decode("utf-8")


def coordinate(expression):
    values = [0, 0, 0, Fraction(0)]
    for term in re.findall(r"[+-]?[^+-]+", expression.replace(" ", "")):
        sign = -1 if term.startswith("-") else 1
        unsigned = term.lstrip("+-")
        if unsigned in ("x", "y", "z"):
            values["xyz".index(unsigned)] += sign
        else:
            values[3] += Fraction(term)
    return values


names = json.loads(read("pyxtal/database/symbols.json"))["rod_group"]
rows = list(csv.reader(io.StringIO(read("pyxtal/database/rod.csv"))))
groups = {int(row[0]): ast.literal_eval(row[1])[0] for row in rows[2:]}
assert len(names) == len(groups) == 75
lines = ["// Generated by Tools/generate_rod_groups.py from the PyXtal rod-group database.",
         f"// Source revision: {REVISION}",
         "// MIT license; see Packages/UnitySymmetry/Third Party Notices.md.",
         "// Each operation: nine row-major rotation entries, then translations in twelfths.",
         "internal static class RodGroupData", "{", "    internal static readonly string[] Names = {"]
for start in range(0, 75, 8):
    lines.append("        " + ", ".join(json.dumps(name) for name in names[start:start+8]) + ",")
lines += ["    };", "    internal static readonly sbyte[][] Operations =", "    {"]
count = 0
for number in range(1, 76):
    operations = []
    for expression in groups[number]:
        coords = [coordinate(part) for part in expression.split(",")]
        rotation = [int(value) for row in coords for value in row[:3]]
        assert all(-1 <= value <= 1 for value in rotation)
        translation = [row[3] for row in coords]
        assert translation[0] == translation[1] == 0
        assert all((value * 12).denominator == 1 for value in translation)
        translations = [int(value * 12) for value in translation]
        translations[2] %= 12
        operations.append(rotation + translations)
    identity = [1,0,0,0,1,0,0,0,1,0,0,0]
    operations.remove(identity)
    operations.insert(0, identity)
    lines += [f"        // {number}: {names[number-1]}", "        new sbyte[] {"]
    lines.extend("            " + ", ".join(map(str, operation)) + "," for operation in operations)
    lines.append("        },")
    count += len(operations)
lines += ["    };", "}", ""]
output = ROOT / "Packages/UnitySymmetry/com.ixxy.unitysymmetry/Wallpaper/Runtime/RodGroupData.cs"
output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"Generated {len(groups)} rod groups, {count} operations")
