"""Generate the runtime catalog: uv run --python 3.12 --with spglib==2.7.0 Tools/generate_space_groups.py"""
from pathlib import Path
import spglib

assert spglib.__version__ == "2.7.0"
root = Path(__file__).resolve().parents[1]
output = root / "Packages/UnitySymmetry/com.ixxy.unitysymmetry/Wallpaper/Runtime/SpaceGroupData.cs"
groups = {}
for hall in range(1, 531):
    info = spglib.get_spacegroup_type(hall)
    groups.setdefault(info.number, info)
assert len(groups) == 230
lines = ["// Generated by Tools/generate_space_groups.py from spglib 2.7.0.",
         "// BSD-3-Clause; see Packages/UnitySymmetry/Third Party Notices.md.",
         "// First Hall setting for each international number. Each operation has",
         "// nine row-major rotation entries, then three translations in twelfths.",
         "internal static class SpaceGroupData", "{"]
for field, values in [
    ("string[] Names", [f'\"{groups[n].international_short}\"' for n in range(1, 231)]),
    ("int[] HallNumbers", [str(groups[n].hall_number) for n in range(1, 231)]),
    ("string[] Settings", [f'\"{groups[n].choice}\"' for n in range(1, 231)])
]:
    lines.append(f"    internal static readonly {field} = {{")
    for start in range(0, len(values), 10):
        lines.append("        " + ", ".join(values[start:start+10]) + ",")
    lines.append("    };")
lines += ["    internal static readonly sbyte[][] Operations =", "    {"]
count = 0
for number in range(1, 231):
    info = groups[number]
    data = spglib.get_symmetry_from_database(info.hall_number)
    operations = []
    for rotation, translation in zip(data["rotations"], data["translations"]):
        r = [int(v) for v in rotation.flat]
        assert all(-1 <= v <= 1 for v in r)
        t = [round(float(v % 1) * 12) % 12 for v in translation]
        assert all(abs(float(v % 1) * 12 - round(float(v % 1) * 12)) < 1e-8 for v in translation)
        operations.append(r + t)
    identity = [1,0,0,0,1,0,0,0,1,0,0,0]
    operations.remove(identity)
    operations.insert(0, identity)
    lines.append(f"        // {number}: {info.international_short}, Hall {info.hall_number}, setting {info.choice or 'standard'}")
    lines.append("        new sbyte[] {")
    lines.extend("            " + ", ".join(map(str, operation)) + "," for operation in operations)
    lines.append("        },")
    count += len(operations)
lines += ["    };", "}", ""]
output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"Generated {len(groups)} groups, {count} operations")
